stages:
  training:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/pipeline/training_pipeline.py
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
      - src/components/model_evaluation.py
  
    outs:
      - 'artifact/raw.csv'
      - 'artifact/train.csv'
      - 'artifact/test.csv'
      - 'artifact/preprocessor.pkl'
      - 'artifact/model.pkl'
