


# this file is use to deploy the code on PYPI

# A python-publish.yaml file in a GitHub workflow typically refers to a YAML file used to define a 'GitHub Actions workflow' for 
# *publishing Python packages* to a package repository such as PyPI (Python Package Index).

# In GitHub Actions, workflows are defined using YAML files that reside in the .github/workflows directory of your repository. 
# These workflows automate tasks such as building, testing, and deploying your code.

# A python-publish.yaml file would specifically define the workflow for publishing a Python package. Here's a simplified example of what such a file might look like



# how to get the workflow  :
# go to project repo in github ,action option 









# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
